import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import { NextAuthProvider } from './Providers'
import { UserProvider } from '@/contexts/UserContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <UserProvider>
        <div className='max-w-3xl mx-auto'>
        <NavBar />
        {children}
        </div>
        </UserProvider>
        </NextAuthProvider>
        </body>
    </html>
  )
}
